<?php

/**
 * BaseArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $text
 * @property clob $image_url
 * 
 * @method string  getTitle()     Returns the current record's "title" value
 * @method clob    getText()      Returns the current record's "text" value
 * @method clob    getImageUrl()  Returns the current record's "image_url" value
 * @method Article setTitle()     Sets the current record's "title" value
 * @method Article setText()      Sets the current record's "text" value
 * @method Article setImageUrl()  Sets the current record's "image_url" value
 * 
 * @package    article
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article');
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 100,
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             'default' => '',
             ));
        $this->hasColumn('image_url', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             'default' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_TimeStampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}