<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/02/24 10:30:37

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tomo;unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
