<?php

/**
 * Article
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    article
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Article extends BaseArticle
{
  public function findTopPagePublishAricles()
  {
    $query = Doctrine_Query::create()
    ->from('Article')
    ->orderBy('rand()')
    ->limit(5);
    
    return $query->execute();
  }

  public function findPublishAricleById($id)
  {
    $query = Doctrine_Query::create()
    ->from('Article')
    ->where('id = ?', $id);

    return $query->execute();
  }

  public function addAriticle($data)
  {
    $article = new Article();
    $article->setTitle($data["title"]);
    $article->setText($data["text"]);
    $article->setImageUrl("https://warambil.files.wordpress.com/2011/02/mylistformwithtasks.gif");
    $article->setCreatedAt(date('Y-m-d H:i:s'));
    $article->save();
  }

  public function editArticle($data)
  {
    $article = Article::findPublishAricleById($data["id"]);
    echo "totyuu error";
    $article->setTitle($data["title"]);
    $article->setText($data["text"]);
    $article->setImageUrl("https://warambil.files.wordpress.com/2011/02/mylistformwithtasks.gif");
    $article->setUpdatedAt(date('Y-m-d H:i:s'));
    $article->save();
  } 

}
