Article:
  actAs:
    TimeStampable: ~
    Sluggable: ~
  columns:
    title:
      type:    string(100)
      notnull: true
      default: ''
    text:
      type:    clob
      notnull: true
      default: ''
    image_url:
      type:    clob
      notnull: true
      default: ''
